name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem would this feature solve? What's the use case?
      placeholder: I'm frustrated when... / I need to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I could also...

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - This would be very valuable
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues and this hasn't been requested before
          required: true
